### ISSUE TITLE
Interested in speaking? 

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2021#9]
Add a little "Interest in speaking?" section. Here's the copy:

Interested in speaking at a conference in 2022? 

[200OK ](https://www.papercall.io/200ok2022)Web Dev Conference (Tulsa, May 2022)
[UXOK Design Conference](https://www.papercall.io/uxok) (Tulsa, July 2022)
[ThunderPlains Web Dev Conference](https://www.papercall.io/thunderplains2022) (OKC, Nov 2022)

**Comment by jsonthebson** [comment]
[feel free to add the logos for those too if that makes it look better ](https://drive.google.com/drive/folders/1MEqMbSdM7MPgaLYwLXIcfMOgtN4d4rp-?usp=sharing)

**Comment by zenlex** [comment]
does this still need to get done?
